// <auto-generated />
using System;
using GestorFinanceiro.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorFinanceiro.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625171901_AdicionarMetaMovimentos")]
    partial class AdicionarMetaMovimentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessaoFinanceiraId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SessaoFinanceiraId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.MetaMovimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("MetaMovimentos");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessaoFinanceiraId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SessaoFinanceiraId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.ReceitaRecorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaDoMes")
                        .HasColumnType("int");

                    b.Property<int>("SessaoFinanceiraId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SessaoFinanceiraId");

                    b.ToTable("ReceitasRecorrentes");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("SessoesFinanceiras");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoFinanceiraCategoria", b =>
                {
                    b.Property<int>("SessaoFinanceiraId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("SessaoFinanceiraId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SessaoFinanceiraCategorias");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Despesa", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("GestorFinanceiro.Data.Models.SessaoFinanceira", "SessaoFinanceira")
                        .WithMany("Despesas")
                        .HasForeignKey("SessaoFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("SessaoFinanceira");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Meta", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.MetaMovimento", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.Meta", "Meta")
                        .WithMany()
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Receita", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.SessaoFinanceira", "SessaoFinanceira")
                        .WithMany("Receitas")
                        .HasForeignKey("SessaoFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessaoFinanceira");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.ReceitaRecorrente", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.SessaoFinanceira", "SessaoFinanceira")
                        .WithMany("ReceitasRecorrentes")
                        .HasForeignKey("SessaoFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessaoFinanceira");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoFinanceira", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.Utilizador", "Utilizador")
                        .WithMany("SessoesFinanceiras")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoFinanceiraCategoria", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.Categoria", "Categoria")
                        .WithMany("SessaoFinanceiraCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorFinanceiro.Data.Models.SessaoFinanceira", "SessaoFinanceira")
                        .WithMany("SessaoFinanceiraCategorias")
                        .HasForeignKey("SessaoFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("SessaoFinanceira");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Categoria", b =>
                {
                    b.Navigation("SessaoFinanceiraCategorias");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoFinanceira", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");

                    b.Navigation("ReceitasRecorrentes");

                    b.Navigation("SessaoFinanceiraCategorias");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Utilizador", b =>
                {
                    b.Navigation("SessoesFinanceiras");
                });
#pragma warning restore 612, 618
        }
    }
}
