// <auto-generated />
using System;
using GestorFinanceiro.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorFinanceiro.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408120739_InicioMigracao")]
    partial class InicioMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessaoGestaoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SessaoGestaoId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoCategoria", b =>
                {
                    b.Property<int>("SessaoGestaoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("SessaoGestaoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SessaoCategorias");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoGestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("SessoesGestao");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Gasto", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.Categoria", "Categoria")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorFinanceiro.Data.Models.SessaoGestao", "SessaoGestao")
                        .WithMany("Gastos")
                        .HasForeignKey("SessaoGestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("SessaoGestao");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoCategoria", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.Categoria", "Categoria")
                        .WithMany("SessaoCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorFinanceiro.Data.Models.SessaoGestao", "SessaoGestao")
                        .WithMany("SessaoCategorias")
                        .HasForeignKey("SessaoGestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("SessaoGestao");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoGestao", b =>
                {
                    b.HasOne("GestorFinanceiro.Data.Models.Utilizador", "Utilizador")
                        .WithMany("SessoesGestao")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Categoria", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("SessaoCategorias");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.SessaoGestao", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("SessaoCategorias");
                });

            modelBuilder.Entity("GestorFinanceiro.Data.Models.Utilizador", b =>
                {
                    b.Navigation("SessoesGestao");
                });
#pragma warning restore 612, 618
        }
    }
}
